/*
Copyright 2020 Sanya K. Waffles

Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

Class SHDX_BlueVase : SHDX_Prop
{
	Default
	{
		//$NotAngled
		//$Title "Blue Vase"
		//$Sprite VASEA0
		//$Category "Obstacles"
		
		Radius 10;
		Height 26;
	}
	
	States
	{
		Spawn:
			VASE A -1;
			Stop;
	}
}

Class SHDX_PottedPlant : SHDX_Prop
{
	Default
	{
		//$NotAngled
		//$Title "Potted Plant"
		//$Sprite PLNTA0
		//$Category "Obstacles"
		
		Radius 10;
		Height 60;
	}
	
	States
	{
		Spawn:
			PLNT A -1;
			Stop;
	}
}

Class SHDX_Lamp : SHDX_Prop
{
	Default
	{
		//$NotAngled
		//$Title "Lamp"
		//$Sprite LAMPA0
		//$Category "Light sources"
		
		+SHOOTABLE
		+NOBLOOD
		
		Radius 10;
		Height 56;
		
		Health 1;
		Mass 1000000;
	}
	
	States
	{
		Spawn:
			LAMP A -1;
			Stop;
		
		Death:
			LAMP A 1
			{
				A_SetRenderStyle(1.0, STYLE_Stencil);
				SetShade("FF0000");
			}
			LAMP A 1;
			TNT1 A 0
			{
				A_StartSound("world/glassbreak", CHAN_BODY);
				
				A_SpawnAshFx(self);
			}
			Stop;
	}
}

Class SHDX_Barrel1 : SHDX_Prop
{
	Default
	{
		//$NotAngled
		//$Title "Wooden Barrel"
		//$Sprite BARLA0
		//$Category "Obstacles"
		
		Radius 10;
		Height 28;
	}
	
	States
	{
		Spawn:
			BARL A -1;
			Stop;
	}
}

Class SHDX_Barrel2 : SHDX_Prop
{
	Default
	{
		//$NotAngled
		//$Title "Green Barrel"
		//$Sprite BAR2A0
		//$Category "Obstacles"
		
		Radius 10;
		Height 28;
	}
	
	States
	{
		Spawn:
			BAR2 A -1;
			Stop;
	}
}

Class SHDX_ExplosiveBarrel : SHDX_ExplodeyProp
{
	Default
	{
		//$NotAngled
		//$Title "Explosive Barrel"
		//$Sprite EBARA0
		//$Category "Obstacles"
		
		Radius 10;
		Height 28;
		
		+SHOOTABLE
		+NOBLOOD
		
		Health 10;
		
		Obituary "$SHDX_OB_BARREL";
	}
	
	States
	{
		Spawn:
			EBAR A -1;
			Stop;
		
		Death:
			EXPL A 0 A_StartSound("world/barrelx", CHAN_BODY);
			EXPL A 3 Bright;
			EXPL BCDEFGHI 3 Bright;
			Stop;
	}
}

Class SHDX_LittleCeilingLight : SHDX_Decoration
{
	Default
	{
		//$NotAngled
		//$Title "Little Ceiling Light"
		//$Sprite CLITA0
		//$Category "Light sources"
		
		Radius 10;
		Height 10;
		
		+SpawnCeiling
		+NoGravity
	}
	
	States
	{
		Spawn:
			CLIT A -1 Bright;
			Stop;
	}
}

Class SHDX_LittleFloorLight : SHDX_Decoration
{
	Default
	{
		//$NotAngled
		//$Title "Little Floor Light"
		//$Sprite FLT2A0
		//$Category "Light sources"
		
		Radius 10;
		Height 10;
	}
	
	States
	{
		Spawn:
			FLT2 A -1 Bright;
			Stop;
	}
}

Class SHDX_Hook : SHDX_Decoration
{
	Default
	{
		//$NotAngled
		//$Title "Hook"
		//$Sprite HOOKA0
		//$Category "Decoration"
		
		Radius 8;
		Height 56;
		
		+SpawnCeiling
		+NoGravity
	}
	
	States
	{
		Spawn:
			HOOK A -1;
			Stop;
	}
}



Class SHDX_Hook2 : SHDX_Hook
{
	Default
	{
		//$NotAngled
		//$Title "Bloody Hook"
		//$Sprite HUK2A0
		//$Category "Decoration"
	}
	
	States
	{
		Spawn:
			HUK2 A -1;
			Stop;
	}
}