/*
Copyright 2020 Sanya K. Waffles

Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/


Class SHDX_SeekerMissileAmmo : Ammo
{
	Default
	{
		Inventory.MaxAmount 7;
		Ammo.BackpackAmount 0;
		Ammo.BackpackMaxAmount 7;
	}
}

Class SHDX_FillySeeker : SHDX_MissileWeapon
{
	Default
	{
		//$Title "Fillyseeker"
		//$Sprite GUN5A0
		
		Weapon.SelectionOrder 350;
		Inventory.PickupMessage "$SHDX_PICKUP_FILLYSEEKER";
		Tag "$SHDX_TAG_FILLYSEEKER";
		+WEAPON.NOAUTOFIRE
		+WEAPON.NOAUTOAIM
		+Weapon.CheatNotWeapon
		Weapon.ammoGive 7;
		Weapon.AmmoUse 1;
		Weapon.AmmoType "SHDX_SeekerMissileAmmo";
		Obituary "$SHDX_OB_FILLYSEEKER";
	}
	
	States
	{
		Ready: 
			HSKG A 1 A_WeaponReady;
			LOOP;
		Deselect:
			HSKG A 1 A_Lower;
			LOOP;
		Select:
			HSKG A 1 A_Raise;
			Loop;
		Flash:
			HSKF A 2 A_Light1;
			goto LightDone;
		Fire: 
			HSKG A 3 A_GunFlash;
			HSKG B 2
			{
				A_StartSound("weapons/fillyf", CHAN_WEAPON);
				A_FireProjectile("SHDX_FillyMissile");
			}
			HSKG B 2;
			HSKG B 2; // ACS_NamedExecute("SHDX_OutOfAmmo", 0, 2)
			HSKG A 2;
			HSKG A 0 A_ReFire;
			Goto Ready;
		Spawn:
			GUN5 A -1;
			LOOP;
	}
}

Class SHDX_FillyMissile : SHDX_Projectile
{
	Default
	{
		Radius 11;
		Height 6;
		Speed 60;
		Damage 10;
		Projectile;
		+SCREENSEEKER
		+SEEKERMISSILE
		DamageType "Explosive";
		// SeeSound "weapons/fillyf";
		DeathSound "weapons/fillyx";
	}
	
	States
	{
		Spawn:
			MISL A 0 NoDelay A_StartSound("weapons/fillyh", CHAN_6, CHANF_LOOPING);
		Spawn1:
			MISL A 1 A_SeekerMissile(5, 5, SMF_LOOK, 256, 10);
			Loop;
		
		Death:
			EXPL A 0 Bright
			{
				A_StopSound(CHAN_6);
				SHDX_Utilities.DoExplosion(self, 56, 32, 80, DamageType:'Explosive');
			}
			EXPL A 3 Bright A_Quake(2, 8, 0, 1096);
			EXPL BCDEFGHI 3 Bright;
			Stop;
	}
}