/*
Copyright 2020 Sanya K. Waffles

Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

Class SHDX_BulletProofArmor : SHDX_Armor
{
	Default
	{
		//$Sprite ARM1A0
		//$Title "Bulletproof Armor"
		//$NonAngled
		//$Category "Health and Armor"
		Radius 12;
		Height 24;
		Scale 0.12;
		Inventory.PickupMessage "$SHDX_PICKUP_BULLETARMOR";
		Inventory.PickupSound "pickup/bulletvest";
		Tag "$SHDX_TAG_BULLETPROOF";
		
		Inventory.Amount 100;
		Inventory.MaxAmount 100;
		Inventory.InterHubAmount 100;
		SHDX_Armor.ArmorPriority 1;
	}

	override int HandleDamage( int damage, Name damageType, int flags )
	{
		double factor;
		if (damageType == 'Bullet')
			factor = .125;
		return int(ceil(damage*factor));
	} 
	
	States
	{
		Spawn:
			ARM1 A -1;
			Stop;
	}
}

Class SHDX_FireProofArmor : SHDX_Armor
{
	Default
	{
		//$Sprite ARM2A0
		//$Title "Fireproof Armor"
		//$NonAngled
		//$Category "Health and Armor"
		Radius 12;
		Height 24;
		Scale 0.12;
		Inventory.PickupMessage "$SHDX_PICKUP_FIREPROOF";
		Inventory.PickupSound "pickup/firevest";
		Tag "$SHDX_TAG_FIREPROOF";
		Inventory.Amount 100;
		Inventory.MaxAmount 100;
		Inventory.InterHubAmount 100;
		SHDX_Armor.ArmorPriority 2;
	}

	override int HandleDamage( int damage, Name damageType, int flags )
	{
		double factor;
		if ((damageType == 'Fire') || (damageType == 'Slime') || (damageType == 'Explosive'))
			factor = .25;
			
		return int(ceil(damage*factor));
	}
	
	States
	{
		Spawn:
			ARM2 A -1;
			Stop;
	}
}

Class SHDX_WeatherProofArmor : SHDX_Armor
{
	Default
	{
		//$Sprite ARM3A0
		//$Title "Weatherproof Armor"
		//$NonAngled
		//$Category "Health and Armor"
		Radius 12;
		Height 24;
		Scale 0.12;
		Inventory.PickupMessage "$SHDX_PICKUP_WEATHERPROOF";
		Inventory.PickupSound "pickup/weathervest";
		Tag "$SHDX_TAG_WEATHERPROOF";
		
		Inventory.Amount 100;
		Inventory.MaxAmount 100;
		Inventory.InterHubAmount 100;
		SHDX_Armor.ArmorPriority 3;
	}

	override int HandleDamage( int damage, Name damageType, int flags )
	{
		double factor;
		
		if ((damageType == 'Weather') || (damageType == 'RainbowX') || (damageType == 'Lightning') || (damageType == 'Ice'))
			factor = .25;
		else if ((damageType == 'Spectra'))
			factor = .125;
		
		return int(ceil(damage*factor));
	}
	
	States
	{
		Spawn:
			ARM3 A -1;
			Stop;
	}
}

Class SHDX_BasicArmor : Inventory
{
	Default
	{
		//$Sprite BARMA0
		//$Title "Basic Armor"
		//$NonAgnled
		//$Category "Health and Armor"
		Radius 12;
		Height 24;
		Scale 0.12;
		Inventory.PickupMessage "$SHDX_PICKUP_BASICARMOR";
		Inventory.PickupSound "pickup/armorvest";
		Tag "$SHDX_TAG_BASICARMOR";
	}
	
	override bool TryPickup(in out Actor toucher)
	{
		
		SHDX_BulletProofArmor barmor = SHDX_BulletProofArmor(toucher.FindInventory("SHDX_BulletProofArmor"));
		SHDX_FireProofArmor farmor = SHDX_FireProofArmor(toucher.FindInventory("SHDX_FireProofArmor"));
		SHDX_WeatherProofArmor warmor = SHDX_WeatherProofArmor(toucher.FindInventory("SHDX_WeatherProofArmor"));
		
		if ((barmor && barmor.amount >= 50) && (farmor && farmor.amount >= 50) && (warmor && warmor.amount >= 50))
		{
			return false;
		}
		else
		{
			if (!barmor || barmor.amount < 50)
			{
				barmor = SHDX_BulletProofArmor(Spawn("SHDX_BulletProofArmor"));
				barmor.amount = 50;
				barmor.BecomeItem();
				toucher.AddInventory(barmor);
			}
			
			if (!farmor || farmor.amount < 50)
			{
				farmor = SHDX_FireProofArmor(Spawn("SHDX_FireProofArmor"));
				farmor.amount = 50;
				farmor.BecomeItem();
				toucher.AddInventory(farmor);
			}
			
			if (!warmor || warmor.amount < 50)
			{
				warmor = SHDX_WeatherProofArmor(Spawn("SHDX_WeatherProofArmor"));
				warmor.amount = 50;
				warmor.BecomeItem();
				toucher.AddInventory(warmor);
			}
			
			Destroy();
		}
		
		return true;
	}
	
	States
	{
		Spawn:
			BARM A -1;
			Stop;
	}
}

Class SHDX_SuperArmor : Inventory
{
	Default
	{
		//$Sprite SARMA0
		//$Title "Super Armor"
		//$NonAgnled
		//$Category "Health and Armor"
		Radius 12;
		Height 24;
		Scale 0.12;
		Inventory.PickupMessage "$SHDX_PICKUP_SUPERARMOR";
		Inventory.PickupSound "pickup/armorvest";
		Tag "$SHDX_TAG_SUPERARMOR";
	}
	
	override bool TryPickup(in out Actor toucher)
	{
		
		SHDX_BulletProofArmor barmor = SHDX_BulletProofArmor(toucher.FindInventory("SHDX_BulletProofArmor"));
		SHDX_FireProofArmor farmor = SHDX_FireProofArmor(toucher.FindInventory("SHDX_FireProofArmor"));
		SHDX_WeatherProofArmor warmor = SHDX_WeatherProofArmor(toucher.FindInventory("SHDX_WeatherProofArmor"));
		
		if ((barmor && barmor.amount >= 150) && (farmor && farmor.amount >= 150) && (warmor && warmor.amount >= 150))
		{
			return false;
		}
		else
		{
			if (!barmor || barmor.amount < 150)
			{
				barmor = SHDX_BulletProofArmor(Spawn("SHDX_BulletProofArmor"));
				barmor.amount = 150;
				barmor.BecomeItem();
				toucher.AddInventory(barmor);
			}
			
			if (!farmor || farmor.amount < 150)
			{
				farmor = SHDX_FireProofArmor(Spawn("SHDX_FireProofArmor"));
				farmor.amount = 150;
				farmor.BecomeItem();
				toucher.AddInventory(farmor);
			}
			
			if (!warmor || warmor.amount < 150)
			{
				warmor = SHDX_WeatherProofArmor(Spawn("SHDX_WeatherProofArmor"));
				warmor.amount = 150;
				warmor.BecomeItem();
				toucher.AddInventory(warmor);
			}
			
			Destroy();
		}
		
		return true;
	}
	
	States
	{
		Spawn:
			SARM A -1;
			Stop;
	}
}