/*
Copyright 2020 Sanya K. Waffles

Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

Class SHDX_PowerProtectionGiver : PowerupGiver
{
	override bool TryPickup (in out Actor toucher)
	{
		// Don't pick up any armor if we have existing armor...
		let w = toucher.FindInventory("SHDX_PowerProtection", true);
		if (w)
		{
			return false;
		}
		
		return Super.TryPickup(toucher);
	}
}

Class SHDX_PowerProtection : PowerProtection
{
	override void DoEffect()
	{
		Super.DoEffect();
		
		if (Owner && EffectTics == 1)
		{
			Owner.A_StartSound("powerup/disappear", 13);
		}
	}
}

Class SHDX_PowerBulletProof : SHDX_PowerProtection
{
	Default
	{
		DamageFactor "Bullet", 0.50;
	}
}

Class SHDX_BulletproofArmor : SHDX_PowerProtectionGiver
{
	Default
	{
		//$Sprite ARM1A0
		//$Title "Bulletproof Armor"
		//$NonAngled
		//$Category "Powerups"
		Radius 12;
		Height 24;
		Scale 0.12;
		Inventory.MaxAmount 0;
		Inventory.PickupMessage "$SHDX_PICKUP_BULLETARMOR";
		Inventory.PickupSound "pickup/bulletvest";
		Powerup.Type "SHDX_PowerBulletProof";
		Powerup.Duration -30;
		Tag "$SHDX_TAG_BULLETPROOF";
		+INVENTORY.AUTOACTIVATE
	}
	
	States
	{
		Spawn:
			ARM1 A -1;
			Stop;
	}
}

Class SHDX_PowerFireProof : SHDX_PowerProtection
{
	Default
	{
		DamageFactor "Explosive", 0.05;
		DamageFactor "Slime", 0.0;
		DamageFactor "Fire", 0.0;
	}
}

Class SHDX_FireproofArmor : SHDX_PowerProtectionGiver
{
	Default
	{
		//$Sprite ARM2A0
		//$Title "Fireproof Armor"
		//$NonAngled
		//$Category "Powerups"
		Radius 12;
		Height 24;
		Scale 0.12;
		Inventory.MaxAmount 0;
		Inventory.PickupMessage "$SHDX_PICKUP_FIREPROOF";
		Inventory.PickupSound "pickup/firevest";
		Powerup.Type "SHDX_PowerFireProof";
		Powerup.Duration -30;
		Tag "$SHDX_TAG_FIREPROOF";
		+INVENTORY.AUTOACTIVATE
	}
	
	States
	{
		Spawn:
			ARM2 A -1;
			Stop;
	}
}



Class SHDX_PowerWeatherProof : SHDX_PowerProtection
{
	Default
	{
		DamageFactor "Weather", 0.05;
		DamageFactor "RainbowX", 0.05;
		DamageFactor "Lightning", 0.05;
	}
}

Class SHDX_WeatherproofArmor : SHDX_PowerProtectionGiver
{
	Default
	{
		//$Sprite ARM3A0
		//$Title "Weatherproof Armor"
		//$NonAngled
		//$Category "Powerups"
		Radius 12;
		Height 24;
		Scale 0.12;
		Inventory.MaxAmount 0;
		Inventory.PickupMessage "$SHDX_PICKUP_WEATHERPROOF";
		Inventory.PickupSound "pickup/weathervest";
		Powerup.Type "SHDX_PowerWeatherProof";
		Powerup.Duration -30;
		Tag "$SHDX_TAG_WEATHERPROOF";
		+INVENTORY.AUTOACTIVATE
	}
	
	override void DoEffect()
	{
		Super.DoEffect();
		
		if (Owner && EffectTics == 1)
		{
			Owner.A_StartSound("powerup/disappear", 13);
		}
	}
	
	States
	{
		Spawn:
			ARM3 A -1;
			Stop;
	}
}