/*
Copyright 2020 Sanya K. Waffles

Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/


Class SHDX_ScootalooPlayer : SHDX_PlayerPawn
{
	Default
	{
		TeleFogSourceType "SHDX_TeleportFog";
		TeleFogDestType "SHDX_TeleportFog";
		
		Scale 0.14;
		
		Speed 1;
		Health 100;
		Radius 16;
		Height 34;
		Mass 100;
		PainChance 255;
		
		Friction 0.995;
		
		BloodType "SHDX_Blood", "SHDX_Blood", "SHDX_Blood";
		
		Player.MaxHealth 100;
		
		Player.DisplayName "SCOOTALOO";
		Player.StartItem "SHDX_Blaster";
		Player.SoundClass "SCOOTALOO";
		
		Player.WeaponSlot 1, "SHDX_Blaster";
		Player.WeaponSlot 2, "SHDX_SubmachineGun";
		Player.WeaponSlot 3, "SHDX_MissileLauncher", "SHDX_FillySeeker", "SHDX_Tornadozer", "SHDX_Rainbower", "SHDX_Hailer";
		

		Player.ColorRange 144, 159;
		Player.ColorSet 0, "$SHDX_SCOOTALOO_COLORSET1", 144, 159, 159;
		Player.ColorSet 1, "$SHDX_SCOOTALOO_COLORSET2", 32, 47, 47;
		Player.ColorSet 2, "$SHDX_SCOOTALOO_COLORSET3", 48, 63, 63;
		Player.ColorSet 3, "$SHDX_SCOOTALOO_COLORSET4", 112, 127, 124;
		Player.ColorSet 4, "$SHDX_SCOOTALOO_COLORSET5", 160, 175, 172;
		Player.ColorSet 5, "$SHDX_SCOOTALOO_COLORSET6", 0, 15, 8;
		Player.ColorSet 6, "$SHDX_SCOOTALOO_COLORSET7", 80, 95, 90;
		Player.ColorSet 7, "$SHDX_SCOOTALOO_COLORSET8", 72, 79, 75;
		
		Player.DamageScreenColor "FF0000", 0.70;
		Player.DamageScreenColor "FFA500", 0.70, "Explosive";
		Player.DamageScreenColor "F0509A", 0.70, "Warp";
		Player.DamageScreenColor "FF5800", 0.50, "Fire";
		Player.DamageScreenColor "CD7F32", 0.70, "Expand";
		Player.DamageScreenColor "00FF00", 0.70, "Shrink";
		Player.DamageScreenColor "0047AB", 0.70, "Webbing";
		Player.DamageScreenColor "00FF00", 0.70, "Bleach";
		Player.DamageScreenColor "00FF00", 0.70, "Cancer";
		Player.DamageScreenColor "00FF00", 0.70, "Acid";
		
		Player.TeleportFreezeTime 0;
		
		Player.ForwardMove 2, 1;
		Player.SideMove 2, 1;
		
		Player.ViewHeight 26;
		Player.AttackZOffset 8;
		Player.JumpZ 12;
		
		Player.AirCapacity 0;
		
		+NoSkin
		
		SHDX_PlayerPawn.OneLinerPrefix "scootaloo";
	}
	
	override void Tick()
	{
		// to avoid something going on with "voodoo dolls" not performing right
		// or the like.
		
		if (!player || !player.mo || player.mo != self)
		{
			// Only perform the PlayerPawn functionality, nothing more...
			Super.Tick();
			return;	// bailing out...
		}
		
		Super.Tick();	// call any PlayerPawn Tick functionality
	}
	
	override void MarkPreCacheSounds()
	{
		Sound snd;
		for (int i = 1; i < 33; i++)
		{
			snd = String.Format("scootaloo/voiceover%d", i);
			MarkSound(snd);
		}
	}
	
	States
	{
		Spawn:
			SCOO A 6;
			Loop;
			
		See:
			SCOO ABCD 4;
			Loop;
			
		Melee:
			SCOO E 10;
			Goto Spawn;
			
		Missile:
			SCOO D 5 BRIGHT;
			Goto Melee;
			
		Pain:
			SCOO F 4;
			SCOO F 4 A_NewPlayerPain;
			Goto Spawn;
		
		Pain.Water:
			SCOO F 4;
			SCOO F 4 A_NewPlayerPain;
			Goto Spawn;
		
		Death:
		Death.Fire:
			SCOO H 5
			{
				A_StopOneLinerSound();
				DDFunc_PlayerDies();
			}
			SCOO IJK 3;
			SCOO L -1;
			Stop;
		
		Death.Extreme:
		Death.Explosive:
			TNT1 A 0
			{
				A_StopOneLinerSound();
				DDFunc_PlayerDiesXTreem();
			}
			GIBX A 4 A_XScream();
			GIBX BC 4;
			GIBX D 4;
			GIBX E 0 A_PlayerScream();
			GIBX E -1;
			Stop;
		
		Crush:
			GIBX E -1;
			Stop;
	}
}
