/*
Copyright 2020 Sanya K. Waffles

Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

Class SHDX_HighGuardBullet : FastProjectile
{
	Default
	{
		Speed 120;
		Radius 8;
		Height 8;
		DamageFunction Random[HighGuard](3,7);
		DamageType "Bullet";
		Scale 0.12;
		MissileType "SHDX_BulletTrail";
		MissileHeight 8;
		RenderStyle "Translucent";
		Alpha 0.667;
		
		+CANNOTPUSH
		+NODAMAGETHRUST
		+SPAWNSOUNDSOURCE
		//+ALLOWTHRUFLAGS
		//+THRUSPECIES
		//+MTHRUSPECIES
		+BloodSplatter
	}
	States
	{
		Spawn:
			BULL A 4 Bright;
			Loop;
		Death:
			PUFF ABCD 4 Bright;
			Stop;
	}
}

/*
Class SHDX_HighGuardSpawner : RandomSpawner
{
	Default
	{
		//$Category "Monsters"
		//$Sprite HIGHF0
		//$Title "High Guard (Random)"
		scale 0.12;
		Radius 20;
		Height 56;
		DropItem "SHDX_HighGuardMale", 255, 7;
		DropItem "SHDX_HighGuardFemale", 255, 13;
	}
} */

Class SHDX_HighGuard : SHDX_Enemy
{
	Default
	{
		//$Category "Monsters"
		//$Sprite HIGHA1
		//$Title "High Guard"
		
		Health 70;
		Radius 20;
		Height 56;
		Mass 100;
		Speed 8;
		PainChance 200;
		SeeSound "hguard1/sight";
		PainSound "hguard1/pain";
		DeathSound "hguard1/death";
		ActiveSound "hguard1/active";
		Obituary "$SHDX_OB_HIGHGUARD";
		Tag "$SHDX_TAG_HIGHGUARD";
		Species "Pony";
	}
	
	void A_DropItemsHighGuard()
	{
		if (target && target.CountInv("SHDX_BitCoin") < 50)
		{
			A_SHDX_DropItem("SHDX_SilverBitCoin", false);
		}
		
		if (target && target.CountInv("SHDX_SubmachineGun") < 1)
			A_SHDX_DropItem("SHDX_SubmachineGun");
	}
	
	void A_HighGuardFire()
	{
		A_StartSound("hguard/attack", CHAN_WEAPON);
		A_SpawnProjectile("SHDX_HighGuardBullet", 32);
	}
	
	States
	{		
		Spawn:
			HIGH A 10 A_Look;
			Loop;
		See:
			HIGH BCDEBCDE 4 A_Chase;
			Loop;
		Missile:
			HIGH F 2 A_FaceTarget;
			HIGH G 2 Bright A_HighGuardFire;
			HIGH H 2;
			HIGH F 2 A_FaceTarget;
			HIGH G 2 Bright A_HighGuardFire;
			HIGH H 2;
			HIGH F 2 A_FaceTarget;
			HIGH G 2 Bright A_HighGuardFire;
			HIGH H 2;
			HIGH F 2 A_FaceTarget;
			HIGH G 2 Bright A_HighGuardFire;
			HIGH H 2;
			Goto See;
		Pain:
			HIGH K 3;
			HIGH K 3 A_Pain;
			Goto See;
		Death:
			HIGH L 5 A_NewScream;
			HIGH M 5
			{
				A_NoBlocking();
				A_DropItemsHighGuard();
			}
			HIGH N 5;
			HIGH O -1 A_SetCorpseShootable;
			Stop;
		Ice:
			HIGH K 5
			{
				A_GenericFreezeDeath();
			}
			HIGH K 1
			{
				A_FreezeDeathChunks();
			}
			Wait;
		Death.Explosive:
		Death.Weather:
		Death.Extreme:
		XDeath:
			GIBX A 3
			{
				A_SHDX_ExtremeScreamAndUnblock();
				A_DropItemsHighGuard();
				A_SpawnGibsFx(self);
			}
			GIBX B 0 A_SHDX_GivePlayerOneLiner(SHDX_ONELINER_GIB_CHANCE);
			GIBX BC 5;
			GIBX D -1;
			Stop;
		Death.RainbowerX:
			GIBR A 4;
			GIBR B 0 A_SHDX_GivePlayerOneLiner(SHDX_ONELINER_GIB_CHANCE);
			GIBR BC 4;
			GIBR D -1;
			Stop;
		Crush:
			GIBX D 0 A_SHDX_SquishSound;
			GIBX D 1 A_SHDX_GivePlayerOneLiner;
			GIBX D -1;
			Stop;
	}
}

/*
Class SHDX_HighGuardFemale : SHDX_HighGuardMale
{
	Default
	{
		//$Category "Monsters"
		//$Sprite HIG2A0
		//$Title "High Guard (Female)"
		
		SeeSound "hguard2/sight";
		PainSound "hguard2/pain";
		DeathSound "hguard2/death";
		ActiveSound "hguard2/active";
	}
	
	States
	{		
		Spawn:
			HIG2 A 10 A_Look;
			Loop;
		See:
			HIG2 BCDEBCDE 4 A_Chase;
			Loop;
		Missile:
			HIG2 F 2 A_FaceTarget;
			HIG2 GH 4 Bright A_HighGuardFire;
			HIG2 IF 2 A_FaceTarget;
			HIG2 GH 4 Bright A_HighGuardFire;
			HIG2 I 2;
			Goto See;
		Pain:
			HIG2 I 0
			{
				if (Random[HighGuard](0, 100) < 50)
					return ResolveState("Pain2");
				
				return ResolveState("Pain1");
			}
		Pain1:
			HIG2 J 3;
			HIG2 J 3 A_Pain;
			Goto See;
		Pain2:
			HIG2 K 3;
			HIG2 K 3 A_Pain;
			Goto See;
		Death:
			HIG2 L 5 A_NewScream;
			HIG2 M 5
			{
				A_NoBlocking();
				A_DropItemsHighGuard();
			}
			HIG2 N 5;
			HIG2 O -1 A_SetCorpseShootable;
			Stop;
		Ice:
			HIG2 J 5
			{
				A_GenericFreezeDeath();
			}
			HIG2 J 1
			{
				A_FreezeDeathChunks();
			}
			Wait;
	}
}
*/

Class SHDX_RocketGuardMissile : SHDX_Missile
{
	Default
	{
		Radius 11;
		Height 8;
		Speed 30;
		Damage 6;
		Projectile;
		+RANDOMIZE
		DamageType "Explosive";
		SeeSound "weapons/rocketf";
		DeathSound "weapons/rocketx";
		Obituary "$SHDX_OB_MISSILE";
	}
	
	States
	{
		Spawn:
			MISL A 1 Bright;
			Loop;
		
		Death:
			EXPL A 0 Bright
			{
				SHDX_Utilities.DoExplosion(self, 24, 32, 64, DamageType:'Explosive');
			}
			EXPL A 3 Bright A_Quake(2, 8, 0, 1096);
			EXPL BCDEFGHI 3 Bright;
			Stop;
	}
}

Class SHDX_RocketGuard : SHDX_HighGuard
{
	Default
	{
		//$Category "Monsters"
		//$Sprite HIGHI2
		//$Title "Rocket Guard"
		
		Health 100;
		Radius 20;
		Height 56;
		Mass 100;
		Speed 8;
		PainChance 96;
		DamageFactor "Explosive", 0.50;
		Obituary "$SHDX_OB_ROCKETGUARD";
		Tag "$SHDX_TAG_ROCKETGUARD";
		Species "Pony";
		
		Translation "96:111=17:21", "136:143=234:239";
	}
	
	void A_DropItemsRocketGuard()
	{
		if (target && target.CountInv("SHDX_BitCoin") < 50)
		{
			A_SHDX_DropItem("SHDX_SilverBitCoin", false);
		}
	}
	
	void A_RocketGuardFire()
	{
		A_SpawnProjectile("SHDX_RocketGuardMissile", 32, -16);
		A_SpawnProjectile("SHDX_RocketGuardMissile", 32, 16);
	}
	
	States
	{
		Missile:
			HIGH A 40
			{
				bNoPain = true;
				A_StartSound("rocketguard/loading", CHAN_WEAPON, attenuation:0.5);
				A_FaceTarget();
			}
			HIGH A 2 A_FaceTarget;
			HIGH I 2 Bright A_RocketGuardFire;
			HIGH J 2
			{
				bNoPain = false;
			}
			Goto See;
		Pain:
			HIGH K 3;
			HIGH K 3 A_Pain;
			Goto See;
		Death:
			HIGH L 5 A_NewScream;
			HIGH M 5
			{
				A_NoBlocking();
				A_DropItemsRocketGuard();
			}
			HIGH N 5;
			HIGH O -1 A_SetCorpseShootable;
			Stop;
		Ice:
			HIGH K 5
			{
				A_GenericFreezeDeath();
			}
			HIGH K 1
			{
				A_FreezeDeathChunks();
			}
			Wait;
		Death.Explosive:
		Death.Weather:
		Death.Extreme:
		XDeath:
			GIBX A 3
			{
				A_SHDX_ExtremeScreamAndUnblock();
				A_DropItemsRocketGuard();
				A_SpawnGibsFx(self);
			}
			GIBX B 0 A_SHDX_GivePlayerOneLiner(SHDX_ONELINER_GIB_CHANCE);
			GIBX BC 5;
			GIBX D -1;
			Stop;
	}
}

Class SHDX_GrenadeGuard : SHDX_HighGuard
{
	Default
	{
		//$Category "Monsters"
		//$Sprite HIGHJ2
		//$Title "Rocket Guard"
		
		Health 100;
		Radius 20;
		Height 56;
		Mass 100;
		Speed 8;
		PainChance 96;
		DamageFactor "Explosive", 0.50;
		Obituary "$SHDX_OB_GRENADEGUARD";
		Tag "$SHDX_TAG_GRENADEGUARD";
		Species "Pony";
		
		Translation "96:111=64:70", "136:143=36:42";
	}
	
	void A_DropItemsGrenadeGuard()
	{
		if (target && target.CountInv("SHDX_BitCoin") < 50)
		{
			A_SHDX_DropItem("SHDX_SilverBitCoin", false);
		}
	}
	
	void A_GrenadeGuardFire()
	{
		A_SpawnProjectile("SHDX_Grenade", 32, -16);
		A_SpawnProjectile("SHDX_Grenade", 32, 16);
	}
	
	States
	{
		Missile:
			HIGH A 40
			{
				bNoPain = true;
				A_StartSound("rocketguard/loading", CHAN_WEAPON, attenuation:0.5);
				A_FaceTarget();
			}
			HIGH A 2 A_FaceTarget;
			HIGH I 2 Bright A_GrenadeGuardFire;
			HIGH J 2
			{
				bNoPain = false;
			}
			Goto See;
		Pain:
			HIGH K 3;
			HIGH K 3 A_Pain;
			Goto See;
		Death:
			HIGH L 5 A_NewScream;
			HIGH M 5
			{
				A_NoBlocking();
				A_DropItemsGrenadeGuard();
			}
			HIGH N 5;
			HIGH O -1 A_SetCorpseShootable;
			Stop;
		Ice:
			HIGH K 5
			{
				A_GenericFreezeDeath();
			}
			HIGH K 1
			{
				A_FreezeDeathChunks();
			}
			Wait;
		Death.Explosive:
		Death.Weather:
		Death.Extreme:
		XDeath:
			GIBX A 3
			{
				A_SHDX_ExtremeScreamAndUnblock();
				A_DropItemsGrenadeGuard();
				A_SpawnGibsFx(self);
			}
			GIBX B 0 A_SHDX_GivePlayerOneLiner(SHDX_ONELINER_GIB_CHANCE);
			GIBX BC 5;
			GIBX D -1;
			Stop;
	}
}