/*
Copyright 2020-2021 Sanya K. Waffles

Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/


Class SHDX_RocketGuard : SHDX_HighGuard
{
	Default
	{
		//$Category "Monsters"
		//$Sprite HIGHI2
		//$Title "Rocket Guard"
		
		Health 100;
		Radius 20;
		Height 56;
		Mass 100;
		Speed 8;
		PainChance 96;
		DamageFactor "Explosive", 0.50;
		Obituary "$SHDX_OB_ROCKETGUARD";
		Tag "$SHDX_TAG_ROCKETGUARD";
		Species "Pony";
		
		Translation "96:111=17:21", "136:143=234:239";
	}
	
	void A_DropItemsRocketGuard()
	{
		if (target && target.CountInv("SHDX_BitCoin") < 50)
			A_SHDX_DropItem("SHDX_SilverBitCoin", false);
	}
	
	void A_RocketGuardFire()
	{
		A_SpawnProjectile("SHDX_RocketGuardMissile", 32, -16);
		A_SpawnProjectile("SHDX_RocketGuardMissile", 32, 16);
	}
	
	States
	{
		Missile:
			HIGH A 40
			{
				bNoPain = true;
				A_StartSound("rocketguard/loading", CHAN_WEAPON, attenuation:0.5);
				A_FaceTarget();
			}
			HIGH A 2 A_FaceTarget;
			HIGH I 2 Bright A_RocketGuardFire;
			HIGH J 2
			{
				bNoPain = false;
			}
			Goto See;
		Pain:
			HIGH K 3;
			HIGH K 3 A_Pain;
			Goto See;
		Death:
			HIGH L 0 A_ResetTranslation;
			HIGH L 5 A_NewScream;
			HIGH M 5
			{
				A_NoBlocking();
				A_DropItemsRocketGuard();
				A_SHDX_GivePlayerOneLiner(SHDX_ONELINER_NORMAL_CHANCE);
			}
			HIGH N 5;
			HIGH O -1 A_SetCorpseShootable;
			Stop;
		Death.Lightning:
			HIGH L 0 A_ResetTranslation;
			HIGH L 5 A_NewScream;
			HIGH M 5
			{
				A_NoBlocking();
				A_DropItemsRocketGuard();
				A_SHDX_GivePlayerOneLiner(SHDX_ONELINER_NORMAL_CHANCE, oltype:OLTYPE_LIGHTNING);
			}
			HIGH N 5;
			HIGH O -1 A_SetCorpseShootable;
			Stop;
		Ice:
			HIGH K 0 A_SHDX_GivePlayerOneLiner(SHDX_ONELINER_NORMAL_CHANCE, oltype:OLTYPE_FROZEN);
			HIGH K 315 A_SHDX_FreezeDeath;
			HIGH K 105 A_SHDX_IceShards;
			Wait;
		Death.Explosive:
			GIBX A 0 A_ResetTranslation;
			GIBX A 3
			{
				A_SHDX_ExtremeScreamAndUnblock();
				A_DropItemsRocketGuard();
				A_SpawnGibsFx(self);
			}
			Goto Super::Death.Explosive;
		Death.Weather:
			GIBX A 0 A_ResetTranslation;
			GIBX A 3
			{
				A_SHDX_ExtremeScreamAndUnblock();
				A_DropItemsRocketGuard();
				A_SpawnGibsFx(self);
			}
			Goto Super::Death.Weather;
		Death.Extreme:
			GIBX A 0 A_ResetTranslation;
			GIBX A 3
			{
				A_SHDX_ExtremeScreamAndUnblock();
				A_DropItemsRocketGuard();
				A_SpawnGibsFx(self);
			}
			Goto Super::Death.Extreme;
		Crush:
			GIBX D 0 A_SHDX_SquishSound;
			GIBX D 1;
			GIBX D -1;
			Stop;
	}
}

Class SHDX_GuardGrenade : SHDX_Grenade
{
	Default
	{
		Damage 4;
		BounceCount 3;
		
		Translation "16:31=144:159";
		
		Scale 0.12;
	}

	States
	{
		Spawn:
			GREN ABCD 1 Bright;
			GREN D 0 Bright
			{
				bNoGravity = false;
			}
			GREN ABCD 1 Bright;
			Loop;
		
		Death:
			EXPL A 3 Bright
			{
				A_SetRenderStyle(0.9, STYLE_Add);
				A_Explode(18, 80, damagetype:'Explosive');
				// SHDX_Utilities.DoExplosion(self, 48, 128., 80, flags:DE_EXTRAZTHRUST);
				A_Stop();
			}
			EXPL B 3 Bright
			{
				A_Quake(2, 8, 0, 1096);
				A_Stop();
			}
			EXPL CDEFGHI 3 Bright
			{
				A_FadeOut(0.1);
				A_Stop();
			}
			Stop;
	}
}

Class SHDX_GrenadeGuard : SHDX_HighGuard
{
	Default
	{
		//$Category "Monsters"
		//$Sprite HIGHJ2
		//$Title "Grenade Guard"
		
		Health 100;
		Radius 20;
		Height 56;
		Mass 100;
		Speed 8;
		PainChance 96;
		DamageFactor "Explosive", 0.50;
		Obituary "$SHDX_OB_GRENADEGUARD";
		Tag "$SHDX_TAG_GRENADEGUARD";
		Species "Pony";
		
		Translation "96:111=64:70", "136:143=36:42";
	}
	
	void A_DropItemsGrenadeGuard()
	{
		if (target && target.CountInv("SHDX_BitCoin") < 50)
			A_SHDX_DropItem("SHDX_SilverBitCoin", false);
	}
	
	void A_GrenadeGuardFire()
	{
		A_StartSound("grenadeguard/fire", CHAN_5);
		A_SpawnProjectile("SHDX_GuardGrenade", 32, -16);
		A_SpawnProjectile("SHDX_GuardGrenade", 32, 16);
	}
	
	States
	{
		Missile:
			HIGH A 40
			{
				bNoPain = true;
				A_StartSound("rocketguard/loading", CHAN_WEAPON, attenuation:0.5);
				A_FaceTarget();
			}
			HIGH A 2 A_FaceTarget;
			HIGH I 2 Bright A_GrenadeGuardFire;
			HIGH J 2
			{
				bNoPain = false;
			}
			Goto See;
		Pain:
			HIGH K 3;
			HIGH K 3 A_Pain;
			Goto See;
		Death:
			HIGH L 0 A_ResetTranslation;
			HIGH L 5 A_NewScream;
			HIGH M 5
			{
				A_NoBlocking();
				A_DropItemsGrenadeGuard();
				A_SHDX_GivePlayerOneLiner(SHDX_ONELINER_NORMAL_CHANCE);
			}
			HIGH N 5;
			HIGH O -1 A_SetCorpseShootable;
			Stop;
		Death.Lightning:
			HIGH L 0 A_ResetTranslation;
			HIGH L 5 A_NewScream;
			HIGH M 5
			{
				A_NoBlocking();
				A_DropItemsGrenadeGuard();
				A_SHDX_GivePlayerOneLiner(SHDX_ONELINER_NORMAL_CHANCE, oltype:OLTYPE_LIGHTNING);
			}
			HIGH N 5;
			HIGH O -1 A_SetCorpseShootable;
			Stop;
		Ice:
			HIGH K 0 A_SHDX_GivePlayerOneLiner(SHDX_ONELINER_NORMAL_CHANCE, oltype:OLTYPE_FROZEN);
			HIGH K 315 A_SHDX_FreezeDeath;
			HIGH K 105 A_SHDX_IceShards;
			Wait;
		Death.Explosive:
			GIBX A 0 A_ResetTranslation;
			GIBX A 3
			{
				A_SHDX_ExtremeScreamAndUnblock();
				A_DropItemsGrenadeGuard();
				A_SpawnGibsFx(self);
			}
			Goto Super::Death.Explosive;
		Death.Weather:
			GIBX A 0 A_ResetTranslation;
			GIBX A 3
			{
				A_SHDX_ExtremeScreamAndUnblock();
				A_DropItemsGrenadeGuard();
				A_SpawnGibsFx(self);
			}
			Goto Super::Death.Weather;
		Death.Extreme:
			GIBX A 0 A_ResetTranslation;
			GIBX A 3
			{
				A_SHDX_ExtremeScreamAndUnblock();
				A_DropItemsGrenadeGuard();
				A_SpawnGibsFx(self);
			}
			Goto Super::Death.Extreme;
		Crush:
			GIBX D 0 A_SHDX_SquishSound;
			GIBX D 1;
			GIBX D -1;
			Stop;
	}
}